"""notificaciones completas

Revision ID: 2f598eb91171
Revises: b4375d00a25c
Create Date: 2026-08-18 19:47:17.539785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f598eb91171'
down_revision: Union[str, Sequence[str], None] = 'b4375d00a25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencias_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('email_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tipo', name='uq_preferencia_usuario_tipo')
    )
    with op.batch_alter_table('preferencias_notificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferencias_notificacion_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=60), server_default='legacy', nullable=False))
        batch_op.add_column(sa.Column('entidad_tipo', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('entidad_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_notificaciones_pendiente', ['consorcio_id', 'entidad_tipo', 'entidad_id', 'leida'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_tipo'))
        batch_op.drop_index('ix_notificaciones_pendiente')
        batch_op.drop_column('entidad_id')
        batch_op.drop_column('entidad_tipo')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('preferencias_notificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferencias_notificacion_usuario_id'))

    op.drop_table('preferencias_notificacion')
    # ### end Alembic commands ###
