"""esquema base

Revision ID: b388a9ef4d2f
Revises: 
Create Date: 2026-08-18 00:14:55.433666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b388a9ef4d2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=False),
    sa.Column('email_contacto', sa.String(length=255), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('modulos_habilitados', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit')
    )
    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('efectivo', 'banco', 'fondo_reparacion', 'otro', name='tipo_caja'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'nombre', name='uq_caja_consorcio_nombre')
    )
    with op.batch_alter_table('cajas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cajas_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('consorcios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administracion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('usa_personal_propio', sa.Boolean(), nullable=False),
    sa.Column('consorcio_domicilio', sa.String(length=500), nullable=False),
    sa.Column('consorcio_cuit', sa.String(length=13), nullable=False),
    sa.Column('consorcio_convenio_suterh', sa.String(length=50), nullable=True),
    sa.Column('admin_nombre', sa.String(length=255), nullable=False),
    sa.Column('admin_domicilio', sa.String(length=500), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('admin_telefono', sa.String(length=50), nullable=False),
    sa.Column('admin_cuit', sa.String(length=13), nullable=False),
    sa.Column('admin_rpa', sa.String(length=50), nullable=False),
    sa.Column('admin_situacion_fiscal', sa.String(length=100), nullable=False),
    sa.Column('banco_titular', sa.String(length=255), nullable=False),
    sa.Column('banco_nombre', sa.String(length=100), nullable=False),
    sa.Column('banco_sucursal', sa.String(length=50), nullable=True),
    sa.Column('banco_numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('banco_cbu', sa.String(length=22), nullable=False),
    sa.Column('banco_alias', sa.String(length=50), nullable=True),
    sa.Column('dia_primer_vencimiento', sa.Integer(), nullable=False),
    sa.Column('dias_entre_vencimientos', sa.Integer(), nullable=False),
    sa.Column('recargo_segundo_vencimiento_pct', sa.Float(), nullable=False),
    sa.Column('tasa_interes_mensual_pct', sa.Float(), nullable=False),
    sa.Column('caja_default_pagos_id', sa.Integer(), nullable=True),
    sa.Column('reportes_visibles_a_depto', sa.Boolean(), nullable=False),
    sa.Column('peticiones_visibles_a_depto', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['administracion_id'], ['administraciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['caja_default_pagos_id'], ['cajas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consorcios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consorcios_administracion_id'), ['administracion_id'], unique=False)

    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('presentado', 'aprobado', 'rechazado', name='estado_presupuesto'), nullable=False),
    sa.Column('fecha_presentacion', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('archivo_path', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_trabajo_id'), ['trabajo_id'], unique=False)

    op.create_table('trabajos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('peticion_id', sa.Integer(), nullable=True),
    sa.Column('presupuesto_aprobado_id', sa.Integer(), nullable=True),
    sa.Column('gasto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('estado', sa.Enum('en_curso', 'finalizado', 'cancelado', name='estado_trabajo'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.ForeignKeyConstraint(['peticion_id'], ['peticiones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_aprobado_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trabajos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trabajos_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trabajos_peticion_id'), ['peticion_id'], unique=False)

    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('precio_reserva', sa.Float(), nullable=True),
    sa.Column('duracion_maxima_horas', sa.Integer(), nullable=True),
    sa.Column('anticipacion_maxima_dias', sa.Integer(), nullable=True),
    sa.Column('max_reservas_activas_por_depto', sa.Integer(), nullable=True),
    sa.Column('horas_minimas_cancelacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'nombre', name='uq_amenity_consorcio_nombre')
    )
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amenities_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('clases_prorrateo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'codigo', name='uq_clase_consorcio_codigo')
    )
    with op.batch_alter_table('clases_prorrateo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clases_prorrateo_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'codigo', name='uq_depto_consorcio_codigo')
    )
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departamentos_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('haberes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('monto_fijo', 'porcentaje_sobre_basico', 'cantidad_x_valor', name='tipo_haber'), nullable=False),
    sa.Column('valor_default', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'nombre', name='uq_haber_consorcio_nombre')
    )
    with op.batch_alter_table('haberes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_haberes_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cuit', sa.String(length=13), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'cuit', name='uq_proveedor_consorcio_cuit')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('transferencias_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('caja_origen_id', sa.Integer(), nullable=False),
    sa.Column('caja_destino_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caja_destino_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['caja_origen_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transferencias_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transferencias_caja_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('coeficientes_departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('clase_prorrateo_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['clase_prorrateo_id'], ['clases_prorrateo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departamento_id', 'clase_prorrateo_id', name='uq_coef_depto_clase')
    )
    with op.batch_alter_table('coeficientes_departamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coeficientes_departamento_clase_prorrateo_id'), ['clase_prorrateo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coeficientes_departamento_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coeficientes_departamento_departamento_id'), ['departamento_id'], unique=False)

    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('archivo_path', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('pendiente_verificacion', 'aprobado', 'rechazado', name='estado_comprobante'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('eliminado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('caja_destino_id', sa.Integer(), nullable=True),
    sa.Column('motivo_rechazo', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['caja_destino_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comprobantes_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comprobantes_departamento_id'), ['departamento_id'], unique=False)

    op.create_table('conceptos_liquidacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('descuento', 'contribucion', name='tipo_concepto'), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'nombre', name='uq_concepto_consorcio_nombre')
    )
    with op.batch_alter_table('conceptos_liquidacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conceptos_liquidacion_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('cuil', sa.String(length=13), nullable=False),
    sa.Column('categoria', sa.Enum('encargado_permanente_con_vivienda', 'encargado_permanente_sin_vivienda', 'encargado_suplente', 'ayudante', name='categoria_empleado'), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('sueldo_basico', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'cuil', name='uq_empleado_consorcio_cuil')
    )
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleados_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('expensas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('monto_primer_vencimiento', sa.Float(), nullable=False),
    sa.Column('fecha_primer_vencimiento', sa.Date(), nullable=False),
    sa.Column('monto_segundo_vencimiento', sa.Float(), nullable=False),
    sa.Column('fecha_segundo_vencimiento', sa.Date(), nullable=False),
    sa.Column('saldo_anterior', sa.Float(), nullable=False),
    sa.Column('recargo_evaluado', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'departamento_id', 'periodo', name='uq_expensa_consorcio_depto_periodo')
    )
    with op.batch_alter_table('expensas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expensas_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expensas_departamento_id'), ['departamento_id'], unique=False)

    op.create_table('gastos_habituales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rubro', sa.Enum('sueldos_y_cargas_sociales', 'servicios_publicos', 'abonos_y_servicios', 'mantenimiento_partes_comunes', 'trabajos_reparaciones_unidades', 'gastos_bancarios', 'gastos_administracion', 'seguros', 'gastos_generales', name='rubro'), nullable=False),
    sa.Column('clase_prorrateo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.Enum('transferencia', 'debito_automatico', 'cheque', 'efectivo', 'otro', name='forma_pago'), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['clase_prorrateo_id'], ['clases_prorrateo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gastos_habituales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gastos_habituales_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('peticiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'convertida_en_trabajo', 'rechazada', 'cancelada', name='estado_peticion'), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=1000), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peticiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peticiones_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_peticiones_departamento_id'), ['departamento_id'], unique=False)

    op.create_table('trabajos_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('periodicidad', sa.Enum('mensual', 'trimestral', 'semestral', 'anual', name='periodicidad_recurrente'), nullable=False),
    sa.Column('proveedor_sugerido_id', sa.Integer(), nullable=True),
    sa.Column('monto_estimado', sa.Float(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_sugerido_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trabajos_recurrentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trabajos_recurrentes_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('administracion', 'representante', 'departamento', 'super_admin', name='rol'), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('administracion_id', sa.Integer(), nullable=True),
    sa.Column('consorcio_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['administracion_id'], ['administraciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_administracion_id'), ['administracion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('audit_log_super_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('super_admin_usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('administracion_id_afectada', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('detalles', sa.String(length=2000), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['administracion_id_afectada'], ['administraciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['super_admin_usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log_super_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_super_admin_fecha'), ['fecha'], unique=False)

    op.create_table('comunicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.String(length=5000), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('eliminado_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunicados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunicados_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunicados_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('expensa_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('expensa_id', sa.Integer(), nullable=False),
    sa.Column('rubro', sa.Enum('sueldos_y_cargas_sociales', 'servicios_publicos', 'abonos_y_servicios', 'mantenimiento_partes_comunes', 'trabajos_reparaciones_unidades', 'gastos_bancarios', 'gastos_administracion', 'seguros', 'gastos_generales', name='rubro'), nullable=False),
    sa.Column('clase_prorrateo_id', sa.Integer(), nullable=True),
    sa.Column('departamento_origen_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['clase_prorrateo_id'], ['clases_prorrateo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_origen_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expensa_id'], ['expensas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expensa_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expensa_detalle_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expensa_detalle_expensa_id'), ['expensa_id'], unique=False)

    op.create_table('liquidaciones_empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('sueldo_bruto', sa.Float(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empleado_id', 'periodo', name='uq_liquidacion_empleado_periodo')
    )
    with op.batch_alter_table('liquidaciones_empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidaciones_empleado_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidaciones_empleado_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidaciones_empleado_periodo'), ['periodo'], unique=False)

    op.create_table('movimientos_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('expensa_emitida', 'pago_recibido', 'interes_punitorio', 'recargo', 'nota_debito', 'nota_credito', name='tipo_movimiento'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('expensa_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expensa_id'], ['expensas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departamento_id', 'expensa_id', 'tipo', name='uq_movimiento_depto_expensa_tipo')
    )
    with op.batch_alter_table('movimientos_cuenta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_cuenta_comprobante_id'), ['comprobante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_cuenta_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_cuenta_departamento_id'), ['departamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_cuenta_expensa_id'), ['expensa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_cuenta_fecha'), ['fecha'], unique=False)

    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_leida'), ['leida'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('periodos_cerrados',
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cerrado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('total_expensado', sa.Float(), nullable=False),
    sa.Column('total_intereses', sa.Float(), nullable=False),
    sa.Column('cantidad_expensas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cerrado_por_usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('periodo', 'consorcio_id')
    )
    with op.batch_alter_table('periodos_cerrados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodos_cerrados_consorcio_id'), ['consorcio_id'], unique=False)

    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('rubro', sa.Enum('sueldos_y_cargas_sociales', 'servicios_publicos', 'abonos_y_servicios', 'mantenimiento_partes_comunes', 'trabajos_reparaciones_unidades', 'gastos_bancarios', 'gastos_administracion', 'seguros', 'gastos_generales', name='rubro'), nullable=False),
    sa.Column('clase_prorrateo_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.Enum('transferencia', 'debito_automatico', 'cheque', 'efectivo', 'otro', name='forma_pago'), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('pagado', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('fecha_factura', sa.Date(), nullable=True),
    sa.Column('cuota_actual', sa.Integer(), nullable=True),
    sa.Column('cuota_total', sa.Integer(), nullable=True),
    sa.Column('gasto_habitual_id', sa.Integer(), nullable=True),
    sa.Column('liquidacion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['clase_prorrateo_id'], ['clases_prorrateo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gasto_habitual_id'], ['gastos_habituales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones_empleado.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consorcio_id', 'periodo', 'gasto_habitual_id', name='uq_gasto_consorcio_periodo_habitual')
    )
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gastos_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gastos_periodo'), ['periodo'], unique=False)
        batch_op.create_index(batch_op.f('ix_gastos_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('liquidaciones_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('concepto_nombre', sa.String(length=120), nullable=False),
    sa.Column('concepto_tipo', sa.Enum('descuento', 'contribucion', name='tipo_concepto'), nullable=False),
    sa.Column('porcentaje_aplicado', sa.Float(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones_empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidaciones_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidaciones_detalle_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidaciones_detalle_liquidacion_id'), ['liquidacion_id'], unique=False)

    op.create_table('liquidaciones_haber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('monto_fijo', 'porcentaje_sobre_basico', 'cantidad_x_valor', name='tipo_haber'), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones_empleado.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidaciones_haber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidaciones_haber_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidaciones_haber_liquidacion_id'), ['liquidacion_id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('confirmada', 'cancelada', name='estado_reserva'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('movimiento_cuenta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimiento_cuenta_id'], ['movimientos_cuenta.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_amenity_id'), ['amenity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_consorcio_id'), ['consorcio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consorcio_id', sa.Integer(), nullable=False),
    sa.Column('caja_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', 'ajuste', name='tipo_movimiento_caja'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('gasto_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('transferencia_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['consorcio_id'], ['consorcios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_caja_consorcio_id'), ['consorcio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_consorcio_id'))

    op.drop_table('movimientos_caja')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_consorcio_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_amenity_id'))

    op.drop_table('reservas')
    with op.batch_alter_table('liquidaciones_haber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidaciones_haber_liquidacion_id'))
        batch_op.drop_index(batch_op.f('ix_liquidaciones_haber_consorcio_id'))

    op.drop_table('liquidaciones_haber')
    with op.batch_alter_table('liquidaciones_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidaciones_detalle_liquidacion_id'))
        batch_op.drop_index(batch_op.f('ix_liquidaciones_detalle_consorcio_id'))

    op.drop_table('liquidaciones_detalle')
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_gastos_periodo'))
        batch_op.drop_index(batch_op.f('ix_gastos_consorcio_id'))

    op.drop_table('gastos')
    with op.batch_alter_table('periodos_cerrados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodos_cerrados_consorcio_id'))

    op.drop_table('periodos_cerrados')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_leida'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_consorcio_id'))

    op.drop_table('notificaciones')
    with op.batch_alter_table('movimientos_cuenta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_cuenta_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimientos_cuenta_expensa_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_cuenta_departamento_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_cuenta_consorcio_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_cuenta_comprobante_id'))

    op.drop_table('movimientos_cuenta')
    with op.batch_alter_table('liquidaciones_empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidaciones_empleado_periodo'))
        batch_op.drop_index(batch_op.f('ix_liquidaciones_empleado_empleado_id'))
        batch_op.drop_index(batch_op.f('ix_liquidaciones_empleado_consorcio_id'))

    op.drop_table('liquidaciones_empleado')
    with op.batch_alter_table('expensa_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expensa_detalle_expensa_id'))
        batch_op.drop_index(batch_op.f('ix_expensa_detalle_consorcio_id'))

    op.drop_table('expensa_detalle')
    with op.batch_alter_table('comunicados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunicados_consorcio_id'))
        batch_op.drop_index(batch_op.f('ix_comunicados_autor_id'))

    op.drop_table('comunicados')
    with op.batch_alter_table('audit_log_super_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_super_admin_fecha'))

    op.drop_table('audit_log_super_admin')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_consorcio_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_administracion_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('trabajos_recurrentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajos_recurrentes_consorcio_id'))

    op.drop_table('trabajos_recurrentes')
    with op.batch_alter_table('peticiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peticiones_departamento_id'))
        batch_op.drop_index(batch_op.f('ix_peticiones_consorcio_id'))

    op.drop_table('peticiones')
    with op.batch_alter_table('gastos_habituales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_habituales_consorcio_id'))

    op.drop_table('gastos_habituales')
    with op.batch_alter_table('expensas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expensas_departamento_id'))
        batch_op.drop_index(batch_op.f('ix_expensas_consorcio_id'))

    op.drop_table('expensas')
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleados_consorcio_id'))

    op.drop_table('empleados')
    with op.batch_alter_table('conceptos_liquidacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conceptos_liquidacion_consorcio_id'))

    op.drop_table('conceptos_liquidacion')
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comprobantes_departamento_id'))
        batch_op.drop_index(batch_op.f('ix_comprobantes_consorcio_id'))

    op.drop_table('comprobantes')
    with op.batch_alter_table('coeficientes_departamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coeficientes_departamento_departamento_id'))
        batch_op.drop_index(batch_op.f('ix_coeficientes_departamento_consorcio_id'))
        batch_op.drop_index(batch_op.f('ix_coeficientes_departamento_clase_prorrateo_id'))

    op.drop_table('coeficientes_departamento')
    with op.batch_alter_table('transferencias_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transferencias_caja_consorcio_id'))

    op.drop_table('transferencias_caja')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_consorcio_id'))

    op.drop_table('proveedores')
    with op.batch_alter_table('haberes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_haberes_consorcio_id'))

    op.drop_table('haberes')
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departamentos_consorcio_id'))

    op.drop_table('departamentos')
    with op.batch_alter_table('clases_prorrateo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clases_prorrateo_consorcio_id'))

    op.drop_table('clases_prorrateo')
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amenities_consorcio_id'))

    op.drop_table('amenities')
    with op.batch_alter_table('trabajos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajos_peticion_id'))
        batch_op.drop_index(batch_op.f('ix_trabajos_consorcio_id'))

    op.drop_table('trabajos')
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_trabajo_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_consorcio_id'))

    op.drop_table('presupuestos')
    with op.batch_alter_table('consorcios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consorcios_administracion_id'))

    op.drop_table('consorcios')
    with op.batch_alter_table('cajas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cajas_consorcio_id'))

    op.drop_table('cajas')
    op.drop_table('administraciones')
    # ### end Alembic commands ###
