"""registro de errores

Revision ID: b4375d00a25c
Revises: fcc0f7af6749
Create Date: 2026-08-18 14:59:55.184145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4375d00a25c'
down_revision: Union[str, Sequence[str], None] = 'fcc0f7af6749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errores_registrados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=16), nullable=False),
    sa.Column('ocurrido_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ruta', sa.String(length=255), nullable=False),
    sa.Column('metodo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('mensaje', sa.String(length=1000), nullable=False),
    sa.Column('traza', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=40), nullable=True),
    sa.Column('consorcio_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('errores_registrados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_errores_registrados_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_errores_registrados_ocurrido_at'), ['ocurrido_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errores_registrados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errores_registrados_ocurrido_at'))
        batch_op.drop_index(batch_op.f('ix_errores_registrados_codigo'))

    op.drop_table('errores_registrados')
    # ### end Alembic commands ###
