"""tokens de recuperacion de password

Revision ID: fcc0f7af6749
Revises: b388a9ef4d2f
Create Date: 2026-08-18 12:15:10.529625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc0f7af6749'
down_revision: Union[str, Sequence[str], None] = 'b388a9ef4d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_recuperacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_recuperacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_recuperacion_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_recuperacion_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_recuperacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_recuperacion_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_recuperacion_token_hash'))

    op.drop_table('tokens_recuperacion')
    # ### end Alembic commands ###
